INSERT INTO "public"."g2p_attribute_values" ("value_id", "attribute_id", "value_code", "value_display", "parent_value_id", "sort_order") VALUES
-- Source of Income
('SOI_CROP_PRODUCTION', 'SOURCE_OF_INCOME', 'CROP_PRODUCTION', 'Crop Production', NULL, 1),
('SOI_LIVESTOCK_PRODUCTION', 'SOURCE_OF_INCOME', 'LIVESTOCK_PRODUCTION', 'Livestock Production', NULL, 2),
('SOI_GOVT_NGO_SUPPORT', 'SOURCE_OF_INCOME', 'GOVT_NGO_SUPPORT', 'Government / NGO Support', NULL, 3),
('SOI_OTHERS', 'SOURCE_OF_INCOME', 'OTHERS', 'Others', NULL, 4),


-- Crop Commodity
('CROP_WHEAT', 'CROP_COMMODITY', 'WHEAT', 'Wheat', NULL, 1),
('CROP_TEFF', 'CROP_COMMODITY', 'TEFF', 'Teff', NULL, 2),
('CROP_MAIZE', 'CROP_COMMODITY', 'MAIZE', 'Maize', NULL, 3),
('CROP_SESAME', 'CROP_COMMODITY', 'SESAME', 'Sesame', NULL, 4),
('CROP_MALT_BARLEY', 'CROP_COMMODITY', 'MALT_BARLEY', 'Malt Barley', NULL, 5),
('CROP_TOMATO', 'CROP_COMMODITY', 'TOMATO', 'Tomato', NULL, 6),
('CROP_ONION', 'CROP_COMMODITY', 'ONION', 'Onion', NULL, 7),
('CROP_AVOCADO', 'CROP_COMMODITY', 'AVOCADO', 'Avocado', NULL, 8),
('CROP_BANANA', 'CROP_COMMODITY', 'BANANA', 'Banana', NULL, 9),
('CROP_MANGO', 'CROP_COMMODITY', 'MANGO', 'Mango', NULL, 10),
('CROP_SOYBEAN', 'CROP_COMMODITY', 'SOYBEAN', 'Soybean', NULL, 11),
('CROP_OTHER', 'CROP_COMMODITY', 'OTHER', 'Other', NULL, 12),

-- Crop Season
('SEASON_SUMMER', 'CROP_SEASON', 'SUMMER', 'Summer', NULL, 1),
('SEASON_MONSOON', 'CROP_SEASON', 'MONSOON', 'Monsoon', NULL, 2),
('SEASON_WINTER', 'CROP_SEASON', 'WINTER', 'Winter', NULL, 3),

-- Livestock Type
('LSTK_CATTLE', 'LIVESTOCK_TYPE', 'CATTLE', 'Cattle', NULL, 1),
('LSTK_CAMEL', 'LIVESTOCK_TYPE', 'CAMEL', 'Camel', NULL, 2),
('LSTK_SHEEP', 'LIVESTOCK_TYPE', 'SHEEP', 'Sheep', NULL, 3),
('LSTK_GOAT', 'LIVESTOCK_TYPE', 'GOAT', 'Goat', NULL, 4),
('LSTK_CHICKEN', 'LIVESTOCK_TYPE', 'CHICKEN', 'Chicken', NULL, 5),
('LSTK_DONKEY', 'LIVESTOCK_TYPE', 'DONKEY', 'Donkey', NULL, 6),
('LSTK_HORSE', 'LIVESTOCK_TYPE', 'HORSE', 'Horse', NULL, 7),
('LSTK_MULE', 'LIVESTOCK_TYPE', 'MULE', 'Mule', NULL, 8),

-- Water Source
('WS_RAINFED', 'WATER_SOURCE', 'RAINFED', 'Rainfed', NULL, 1),
('WS_IRRIGATION_GROUND', 'WATER_SOURCE', 'IRRIGATION_GROUND_WATER', 'Irrigation - Ground Water', NULL, 2),
('WS_IRRIGATION_SURFACE', 'WATER_SOURCE', 'IRRIGATION_SURFACE_WATER', 'Irrigation - Surface Water', NULL, 3),
('WS_WELL_GROUND', 'WATER_SOURCE', 'WELL_GROUND_WATER', 'Well Water (Ground Water)', NULL, 4),
('WS_WATER_HARVESTING', 'WATER_SOURCE', 'WATER_HARVESTING', 'Water Harvesting', NULL, 5),
('WS_SURFACE_WATER', 'WATER_SOURCE', 'SURFACE_WATER', 'Surface Water', NULL, 6),

-- Means of Acquisition
('MOA_INHERITANCE', 'MEANS_OF_ACQUISITION', 'INHERITANCE', 'Inheritance', NULL, 1),
('MOA_DONATION_GIFT', 'MEANS_OF_ACQUISITION', 'DONATION_GIFT', 'Donation / Gift', NULL, 2),
('MOA_EXPROPRIATION', 'MEANS_OF_ACQUISITION', 'EXPROPRIATION', 'Expropriation / Land Taking', NULL, 3),
('MOA_RENTING_LEASING', 'MEANS_OF_ACQUISITION', 'RENTING_LEASING', 'Renting / Leasing', NULL, 4),
('MOA_REALLOCATION', 'MEANS_OF_ACQUISITION', 'REALLOCATION', 'Reallocation / Redistribution', NULL, 5),
('MOA_DIVORCE_SETTLEMENT', 'MEANS_OF_ACQUISITION', 'DIVORCE_SETTLEMENT', 'Divorce Settlement', NULL, 6);
