INSERT INTO "public"."g2p_attribute_values" ("value_id","attribute_id","value_code","value_display","parent_value_id","sort_order") VALUES 
-- Source of Income
('SOI_CROP_PRODUCTION','SOURCE_OF_INCOME','CROP_PRODUCTION','Crop Production',NULL,1),
('SOI_LIVESTOCK_PRODUCTION','SOURCE_OF_INCOME','LIVESTOCK_PRODUCTION','Livestock Production',NULL,2),
('SOI_GOVERNMENT_NGO_SUPPORT','SOURCE_OF_INCOME','GOVERNMENT_NGO_SUPPORT','Government / NGO Support',NULL,3),
('SOI_OTHERS','SOURCE_OF_INCOME','OTHERS','Others',NULL,4),
-- Crop Commodity
('CROP_WHEAT','CROP_COMMODITY','WHEAT','WHEAT',NULL,1),
('CROP_TEFF','CROP_COMMODITY','TEFF','TEFF',NULL,2),
('CROP_MAIZE','CROP_COMMODITY','MAIZE','MAIZE',NULL,3),
('CROP_SESAME','CROP_COMMODITY','SESAME','SESAME',NULL,4),
('CROP_MALT_BARLEY','CROP_COMMODITY','MALT_BARLEY','MALT_BARLEY',NULL,5),
('CROP_TOMATO','CROP_COMMODITY','TOMATO','TOMATO',NULL,6),
('CROP_ONION','CROP_COMMODITY','ONION','ONION',NULL,7),
('CROP_AVOCADO','CROP_COMMODITY','AVOCADO','AVOCADO',NULL,8),
('CROP_BANANA','CROP_COMMODITY','BANANA','BANANA',NULL,9),
('CROP_MANGO','CROP_COMMODITY','MANGO','MANGO',NULL,10),
('CROP_SOYBEAN','CROP_COMMODITY','SOYBEAN','SOYBEAN',NULL,11),
('CROP_OTHER','CROP_COMMODITY','OTHER','OTHER',NULL,12),
-- Crop Season
('SEASON_SUMMER','CROP_SEASON','SUMMER','SUMMER',NULL,1),
('SEASON_MONSOON','CROP_SEASON','MONSOON','MONSOON',NULL,2),
('SEASON_WINTER','CROP_SEASON','WINTER','WINTER',NULL,3),
-- Livestock Type
('LSTK_CATTLE','LIVESTOCK_TYPE','CATTLE','CATTLE',NULL,1),
('LSTK_CAMEL','LIVESTOCK_TYPE','CAMEL','CAMEL',NULL,2),
('LSTK_SHEEP','LIVESTOCK_TYPE','SHEEP','SHEEP',NULL,3),
('LSTK_GOAT','LIVESTOCK_TYPE','GOAT','GOAT',NULL,4),
('LSTK_CHICKEN','LIVESTOCK_TYPE','CHICKEN','CHICKEN',NULL,5),
('LSTK_DONKEY','LIVESTOCK_TYPE','DONKEY','DONKEY',NULL,6),
('LSTK_HORSE','LIVESTOCK_TYPE','HORSE','HORSE',NULL,7),
('LSTK_MULE','LIVESTOCK_TYPE','MULE','MULE',NULL,8),
-- Water Source
('WS_RAINFED','WATER_SOURCE','RAINFED','RAINFED',NULL,1),
('WS_IRRIGATION_GROUND','WATER_SOURCE','IRRIGATION_GROUND_WATER','IRRIGATION_GROUND_WATER',NULL,2),
('WS_IRRIGATION_SURFACE','WATER_SOURCE','IRRIGATION_SURFACE_WATER','IRRIGATION_SURFACE_WATER',NULL,3),
('WS_WELL_GROUND','WATER_SOURCE','WELL_GROUND_WATER','WELL_GROUND_WATER',NULL,4),
('WS_WATER_HARVESTING','WATER_SOURCE','WATER_HARVESTING','WATER_HARVESTING',NULL,5),
('WS_SURFACE_WATER','WATER_SOURCE','SURFACE_WATER','SURFACE_WATER',NULL,6),
-- Means of Acquisition
('MOA_INHERITANCE','MEANS_OF_ACQUISITION','INHERITANCE','INHERITANCE',NULL,1),
('MOA_DONATION_GIFT','MEANS_OF_ACQUISITION','DONATION_GIFT','DONATION_GIFT',NULL,2),
('MOA_EXPROPRIATION','MEANS_OF_ACQUISITION','EXPROPRIATION','EXPROPRIATION',NULL,3),
('MOA_RENTING_LEASING','MEANS_OF_ACQUISITION','RENTING_LEASING','RENTING_LEASING',NULL,4),
('MOA_REALLOCATION','MEANS_OF_ACQUISITION','REALLOCATION','REALLOCATION',NULL,5),
('MOA_DIVORCE_SETTLEMENT','MEANS_OF_ACQUISITION','DIVORCE_SETTLEMENT','DIVORCE_SETTLEMENT',NULL,6),
-- Soil Fertility
('SF_HIGH','SOIL_FERTILITY','HIGH','HIGH',NULL,1),
('SF_MEDIUM','SOIL_FERTILITY','MEDIUM','MEDIUM',NULL,2),
('SF_LOW','SOIL_FERTILITY','LOW','LOW',NULL,3),
-- Livestock Breed
('BREED_IMPROVED','LIVESTOCK_BREED','IMPROVED','IMPROVED',NULL,1),
('BREED_LOCAL','LIVESTOCK_BREED','LOCAL','LOCAL',NULL,2),
('BREED_HYBRID','LIVESTOCK_BREED','HYBRID','HYBRID',NULL,3);