from .g2p_register_domain_service_crop import G2PRegisterDomainServiceCrop
from .g2p_register_domain_service_machinery import G2PRegisterDomainServiceMachinery
from .g2p_register_domain_service_farmer import G2PRegisterDomainServiceFarmer
from .g2p_register_domain_service_household import G2PRegisterDomainServiceHousehold
from .g2p_register_domain_service_household_member import G2PRegisterDomainServiceHouseholdMember
from .g2p_register_domain_service_livestock import G2PRegisterDomainServiceLivestock
from .g2p_register_domain_service_land import G2PRegisterDomainServiceLand
